apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-db-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-lrs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enrollment-db-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-lrs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lecturer-db-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-lrs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-db-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi-lrs
  resources:
    requests:
      storage: 1Gi
