name: "Configuration Drift Detection"
on:
  schedule:
  # Run the workflow every day at midnight
    - cron: "0 0 * * *" # This cron expression means "At 00:00 (midnight) every day"
  workflow_dispatch:

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-dr
      - name: Terraform Plan (Drift Check)
        run: terraform plan -detailed-exitcode
        working-directory: ./terraform-dr